import pathlib
import re
P = pathlib.Path("frontend/merchants.html")
s = P.read_text(encoding="utf-8")

RESET_OLD = """    function resetMerchantForm() {\n      merchantEditId = null;\n      merchantStagingUrls = [];\n      document.getElementById('newMerchantName').value = '';\n            document.getElementById('merchantPasteInput').value = '';\n      document.getElementById('merchantFormHeading').textContent = '新增商家';\n      document.getElementById('btnMerchantNewMode').classList.add('hidden');\n      renderMerchantStaging();\n    }"""
RESET_NEW = """    function resetMerchantForm() {\n      merchantEditId = null;\n      merchantStagingUrls = [];\n      jsonStagingSegments = [];\n      merchantEditCatalogSnapshot = [];\n      document.getElementById('newMerchantName').value = '';\n      document.getElementById('merchantPasteInput').value = '';\n      document.getElementById('jsonPaste').value = '';\n      document.getElementById('merchantFormHeading').textContent = '新增商家';\n      document.getElementById('btnMerchantNewMode').classList.add('hidden');\n      renderMerchantStaging();\n      renderJsonStaging();\n    }"""
if RESET_OLD in s:
    s = s.replace(RESET_OLD, RESET_NEW, 1)
    print("reset ok")

RJ = """        wrap.appendChild(chip);\n      });\n    }\n    function addPasteToStaging() {"""
RJNEW = """        wrap.appendChild(chip);\n      });\n    }\n    function renderJsonStaging() {\n      const wrap = document.getElementById('jsonStagingList');\n      const cnt = document.getElementById('jsonStagingCount');\n      if (!wrap || !cnt) return;\n      cnt.textContent = String(jsonStagingSegments.length);\n      wrap.innerHTML = '';\n      jsonStagingSegments.forEach((raw, idx) => {\n        const chip = document.createElement('span');\n        chip.className = 'inline-flex items-center gap-1 max-w-full px-2 py-0.5 rounded bg-violet-50 border border-violet-200 text-xs text-violet-900';\n        const t = document.createElement('span');\n        t.className = 'truncate';\n        const preview = raw.replace(/\\s+/g, ' ').trim();\n        t.title = preview.slice(0, 500);\n        t.textContent = '段 ' + (idx + 1) + ' · ' + (preview.length > 36 ? preview.slice(0, 34) + '…' : preview);\n        const x = document.createElement('button');\n        x.type = 'button';\n        x.className = 'text-slate-500 hover:text-red-600 shrink-0';\n        x.textContent = '\\u00d7';\n        x.onclick = () => {\n          jsonStagingSegments = jsonStagingSegments.filter((_, i) => i !== idx);\n          renderJsonStaging();\n        };\n        chip.appendChild(t);\n        chip.appendChild(x);\n        wrap.appendChild(chip);\n      });\n    }\n    function addPasteToStaging() {"""
if "function renderJsonStaging" not in s and RJ in s:
    s = s.replace(RJ, RJNEW, 1)
    print("renderJson ok")

SS_OLD = """    function startEditMerchant(id) {\n      const m = merchantsCache.find((x) => x.id === id);\n      if (!m) return;\n      merchantEditId = id;\n      document.getElementById('newMerchantName').value = m.name || '';\n            merchantStagingUrls = (m.sources || []).map((s) => s.url).filter(Boolean);\n      document.getElementById('merchantPasteInput').value = '';\n      document.getElementById('merchantFormHeading').textContent = '\\u7de8\\u8f2f\\u5546\\u5bb6';\n      document.getElementById('btnMerchantNewMode').classList.remove('hidden');\n      renderMerchantStaging();\n    }\n    async function saveMerchantForm() {"""
SS_NEW = """    async function startEditMerchant(id) {\n      const m = merchantsCache.find((x) => x.id === id);\n      if (!m) return;\n      merchantEditId = id;\n      document.getElementById('newMerchantName').value = m.name || '';\n      merchantStagingUrls = (m.sources || []).map((s) => s.url).filter(Boolean);\n      document.getElementById('merchantPasteInput').value = '';\n      document.getElementById('jsonPaste').value = '';\n      jsonStagingSegments = [];\n      renderJsonStaging();\n      merchantEditCatalogSnapshot = [];\n      document.getElementById('merchantFormHeading').textContent = '\\u7de8\\u8f2f\\u5546\\u5bb6';\n      document.getElementById('btnMerchantNewMode').classList.remove('hidden');\n      renderMerchantStaging();\n      try {\n        const r = await fetch('/api/merchants/' + encodeURIComponent(id) + '?_=' + Date.now(), { cache: 'no-store' });\n        const j = await r.json();\n        if (j.ok && j.merchant && Array.isArray(j.merchant.catalogItems)) {\n          merchantEditCatalogSnapshot = j.merchant.catalogItems;\n        }\n      } catch (_) {}\n    }\n    async function saveMerchantForm() {"""
if SS_OLD in s:
    s = s.replace(SS_OLD, SS_NEW, 1)
    print("startEdit ok")

# saveMerchantForm body replace - from async function saveMerchantForm to closing }; before renderMerchantList
pat = re.compile(
    r"async function saveMerchantForm\(\) \{.*?^\    \}",
    re.MULTILINE | re.DOTALL,
)
SAVE_NEW = """async function saveMerchantForm() {\n      const name = document.getElementById('newMerchantName').value.trim();\n      if (!name) { alert('請輸入商家名稱'); return; }\n      const jsonPasteVal = document.getElementById('jsonPaste').value.trim();\n      let newFromJson = [];\n      try {\n        newFromJson = mapFromJsonSegments(jsonStagingSegments, jsonPasteVal);\n      } catch (e) {\n        alert(e.message || 'JSON 解析失敗');\n        return;\n      }\n      const hasNewJson = jsonStagingSegments.length > 0 || jsonPasteVal.length > 0;\n      let catalogItems = null;\n      if (merchantEditId) {\n        if (hasNewJson) {\n          catalogItems = mergeNormalizedCatalogItems(merchantEditCatalogSnapshot || [], newFromJson);\n        }\n      } else {\n        catalogItems = newFromJson;\n      }\n      if (!merchantStagingUrls.length && (!catalogItems || !catalogItems.length)) {\n        if (!merchantEditId || hasNewJson) {\n          alert('請至少加入一個相冊網址，或貼上含商品的 JSON（result.items）');\n          return;\n        }\n      }\n      const sources = merchantStagingUrls.map((u) => ({ url: u }));\n      const wasEdit = !!merchantEditId;\n      const body = { name, sources };\n      if (!wasEdit) {\n        body.catalogItems = catalogItems || [];\n      } else if (catalogItems !== null) {\n        body.catalogItems = catalogItems;\n      }\n      try {\n        let r;\n        if (merchantEditId) {\n          r = await fetch('/api/merchants/' + encodeURIComponent(merchantEditId), {\n            method: 'PUT',\n            headers: { 'Content-Type': 'application/json' },\n            body: JSON.stringify(body),\n          });\n        } else {\n          r = await fetch('/api/merchants', {\n            method: 'POST',\n            headers: { 'Content-Type': 'application/json' },\n            body: JSON.stringify(body),\n          });\n        }\n        const j = await r.json();\n        if (!r.ok) throw new Error(j.message || j.error || '儲存失敗');\n        if (!j.ok) throw new Error(j.message || j.error || '儲存失敗');\n        resetMerchantForm();\n        await loadMerchantsForList();\n        renderMerchantList();\n        alert(wasEdit ? '已儲存' : '已新增');\n      } catch (e) { alert(e.message || '儲存失敗'); }\n    }"""

m = pat.search(s)
if m and "mapFromJsonSegments" not in m.group(0):
    s = pat.sub(SAVE_NEW, s, count=1)
    print("saveMerchant ok")

P.write_text(s, encoding="utf-8")
